apiVersion: v1
kind: Namespace
metadata:
  name: backend
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DATABASE_USER: "postgres"
  DATABASE_DB_NAME: "postgres"
  DATABASE_HOST: "postgres-db.db.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  DATABASE_PASSWORD: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: app
          image: "manjeetsinhalonja/todo-backend:v1"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: backend
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
