services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    image: gcr.io/black-journal-436122-b5/todo-backend:v1
    ports:
      - "5001:5000"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DB_NAME=postgres
      - DATABASE_HOST=postgres
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    image: gcr.io/black-journal-436122-b5/todo-frontend:v1
    ports:
      - target: 8080
        published: 80
        mode: host
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
