wp:
  name: backend
  labels:
    app: backend
    env: dev
  image:
    repository: manjeetsinhalonja/todo-backend
    tag: v1
  replicas: 1
  configmap:
    DATABASE_USER: postgres
    DATABASE_DB_NAME: postgres
    DATABASE_HOST: postgres-db.db.svc.cluster.local
  containerPorts:
      http: 5000
  secrets:
      DATABASE_PASSWORD: postgres
