wp:
  name: backend
  labels:
    app: backend
    env: dev
  image:
    repository: manjeetsinhalonja/todo-backend
    tag: v1
  replicas: 1
  configmap:
    BACKEND_URL: "http://34.172.145.211"
  containerPorts:
      http: 8080
  secrets:
      DATABASE_PASSWORD: {}
