wp:
  name: frontend
  labels:
    app: frontend
    env: dev
  image:
    repository: manjeetsinhalonja/todo-frontend
    tag: v1
  replicas: 1
  configmap:
    BACKEND_URL: "http://34.55.99.38"
  containerPorts:
      http: 8080
  secrets: {}
